//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TraWellDummyEntities : DbContext
    {
        public TraWellDummyEntities()
            : base("name=TraWellDummyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<GuestUser> GuestUsers { get; set; }
        public virtual DbSet<PassengerDetail> PassengerDetails { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripStop> TripStops { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
    
        public virtual ObjectResult<proc_LoginCheck_Result> proc_LoginCheck(string un, string pw)
        {
            var unParameter = un != null ?
                new ObjectParameter("un", un) :
                new ObjectParameter("un", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_LoginCheck_Result>("proc_LoginCheck", unParameter, pwParameter);
        }
    
        public virtual ObjectResult<prc_frequent_routes_Result> prc_frequent_routes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_frequent_routes_Result>("prc_frequent_routes");
        }
    
        public virtual ObjectResult<prc_profit_Result> prc_profit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_profit_Result>("prc_profit");
        }
    
        public virtual ObjectResult<prc_feedback_Result> prc_feedback()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_feedback_Result>("prc_feedback");
        }
    
        public virtual ObjectResult<prc_manage_trips_Result> prc_manage_trips()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_manage_trips_Result>("prc_manage_trips");
        }
    }
}
