//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.PassengerDetails = new HashSet<PassengerDetail>();
            this.Transactions = new HashSet<Transaction>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int BookingID { get; set; }
        public int UserRegistered { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string Status { get; set; }
        public int TripId { get; set; }
        public string Boarding { get; set; }
        public string Arrival { get; set; }
        public string Feedback { get; set; }
        public double Amount { get; set; }
    
        public virtual GuestUser GuestUser { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerDetail> PassengerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
