//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerDetail
    {
        public int BookingID { get; set; }
        public int Seat { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
