//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public decimal amount { get; set; }
        public int BookingID { get; set; }
        public string Mode { get; set; }
        public string TransType { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
