//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraWellApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public int RouteID { get; set; }
        public string Stop1 { get; set; }
        public double DistanceFromOrigin { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Route Route { get; set; }
    }
}
